export const routes = {
  home: "/",
  login: "/login",
  forbidden: "/forbidden",
  dashboard: "/dashboard",
  plants: "/plants",
  interventions: "/interventions",
  tasks: "/tasks",
  today: "/today",
  approvals: "/approvals",
  notifications: "/notifications",
  reports: "/reports",
  offline: "/offline",
  install: "/install",
  scan: "/scan",
  offlineSync: "/offline-sync",
  adminSystem: "/admin/system",
  adminUsers: "/admin/users",
};
